export enum PRODUCT_CATEGORY {
  HOT_DRINK = "HOT_DRINK",
  COLD_DRINK = "COLD_DRINK",
  HEALTHY_DRINK = "HEALTHY_DRINK",
  MILK_BASED = "MILK_BASED",
  ALCOHOLIC = "ALCOHOLIC",
}

export enum PRODUCT_TYPE {
  BLACK_COFFEE = "BLACK_COFFEE",
  LATTE = "LATTE",
  ICED_TEA = "ICED_TEA",
  SMOOTHIE_FRUIT = "SMOOTHIE_FRUIT",
  YOGURT_DRINK = "YOGURT_DRINK",
  CHOCOLATE_MILK = "CHOCOLATE_MILK",
  CRAFT_BEER = "CRAFT_BEER",
}


export const FORM_DEFAULT_VALUE: {
  NUMBER: number | null;
  STRING: string | null;
} = {
  NUMBER: null,
  STRING: null
}
